version: '3.8'
services:
    python-flask:
        container_name: vsnippet-format-injection-classic-32
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:1337
